spring:
  profiles:
    active: dev

---
server:
  port: 9200
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bmv_services?useSSL=false
    username: localuser
    password: 1qazxsw2
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  config:
    activate:
      on-profile: dev
jasperservice:
  certificate: /home/alexander/Documents/integrasoadev-wls-1
  path_out: /home/alexander/GlobalGas/PDFCreatorIntegra/src/main/resources/invoice.pdf
  url: http://alexander-thinkpad-p51:8080/PDFCreatorIntegra-1.8/integra/pdfcreator/
  payment: /home/alexander/GlobalGas/JasperPDFServices/build/resources/main/reports/globalnetInvoiceComplementERP.jasper
  invoice: /media/luis/Data/GIT/JasperPDFServices/src/main/resources/reports/globalnetInvoiceERP.jasper
  subReportInvoice: /media/luis/Data/GIT/JasperPDFServices/src/main/resources/reports/detailsInvoiceERP.jasper
  subReportPayment: /home/alexander/GlobalGas/JasperPDFServices/build/resources/main/reports/doctosRelations.jasper

---
server:
  port: 9099
spring:
  datasource:
    url: jdbc:mysql://10.0.0.85:3306/bmv_services?useSSL=false
    username: crm
    password: G9*&^Sf4cVun=*H5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  config:
    activate:
      on-profile: prod
jasperservice:
  cert: /home/alexander/Documents/integrasoadev-wls-1
  path_out: /home/alexander/GlobalGas/PDFCreatorIntegra/src/main/resources/invoice.pdf
  url: http://alexander-thinkpad-p51:8080/PDFCreatorIntegra-1.8/integra/pdfcreator/
  payment: /home/verse/reports/globalnetInvoiceComplementERP.jasper
  invoice: /home/verse/reports/globalnetInvoiceERP.jasper
  subReportInvoice: /home/verse/reports/detailsInvoiceERP.jasper
  subReportPayment: /home/verse/reports/doctosRelations.jasper

---

server:
  port: 9099
spring:
  datasource:
    url: jdbc:mysql://10.0.0.85:3306/bmv_services?useSSL=false
    username: crm
    password: G9*&^Sf4cVun=*H5
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  config:
    activate:
      on-profile: qa
jasperservice:
  cert: /home/verse/reports/integrasoadev-wls-1
  path_out: /home/alexander/GlobalGas/PDFCreatorIntegra/src/main/resources/invoice.pdf
  url: http://alexander-thinkpad-p51:8080/PDFCreatorIntegra-1.8/integra/pdfcreator/
  payment: /home/verse/reports/globalnetInvoiceComplementERP.jasper
  invoice: /home/verse/reports/globalnetInvoiceERP.jasper
  subReportInvoice: /home/verse/reports/detailsInvoiceERP.jasper
  subReportPayment: /home/verse/reports/doctosRelations.jasper

---

server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bmv_services?useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  config:
    activate:
      on-profile: alex
jasperservice:
  certificate: /home/alexander/Documents/integrasoadev-wls-1
  path_out: /home/alexander/GlobalGas/PDFCreatorIntegra/src/main/resources/invoice.pdf
  url: http://alexander-thinkpad-p51:8080/PDFCreatorIntegra-1.8/integra/pdfcreator/
  payment: /home/alexander/GlobalGas/JasperPDFServices/build/resources/main/reports/globalnetInvoiceComplementERP.jasper
  invoice: /home/alexander/GlobalGas/JasperPDFServices/build/resources/main/reports/globalnetInvoiceERP.jasper
  subReportInvoice: /home/alexander/GlobalGas/JasperPDFServices/build/resources/main/reports/detailsInvoiceERP.jasper
  subReportPayment: /home/alexander/GlobalGas/JasperPDFServices/build/resources/main/reports/doctosRelations.jasper
